POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": "null",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/6bde3d47-b6ba-4131-abfe-06452cfb88c6/attendees
Content-Type: application/json

{
  "name": "Anna",
  "email": "anna@gmail.com"
}

###

GET http://localhost:3333/events/6bde3d47-b6ba-4131-abfe-06452cfb88c6

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/6bde3d47-b6ba-4131-abfe-06452cfb88c6/attendees

# GET http://localhost:3333/events/6bde3d47-b6ba-4131-abfe-06452cfb88c6/attendees?query=mic