POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento teste 2",
  "details": "null",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/374403be-a94d-4997-b2bb-da11a78f3bff/attendees
Content-Type: application/json

{
  "name": "Michelle",
  "email": "email@gmail.com"
}

###

GET http://localhost:3333/events/6bde3d47-b6ba-4131-abfe-06452cfb88c6