POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Global Career Summit",
  "details": "Um evento para quem quer conquistar uma vaga no exterior",
  "maximumAttendees": 200
}